Added FileList.ro torrent provider
SickChill/sickchill pull request #1145
Opened 2016-03-18 21:24 UTC by ovidiub13

I have not tested this, as I don't know how.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

2016-03-18 21:24 UTC, SickRage2 commented
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

2016-03-19 19:24 UTC, ovidiub13 commented
I've tested it and it successfully finds and downloads the desired torrents.

2016-03-19 19:24 UTC, ovidiub13 commented
IMO it can be merged.

2016-03-19 22:34 UTC, miigotu commented
Leave it open for now. I have a few small changes, so later I will pull it, rebase, and fix up the quantifiedCode warnings and a few other small fixes.


Good work

2016-03-27 18:56 UTC, ovidiub13 commented
What's the state of this PR?

2016-03-27 20:23 UTC, miigotu commented
Just need a little time to open up for me lol. I have some local changes for it

2016-10-02 08:31 UTC, ovidiub13 commented
@miigotu Can this still me merged? I can look into the merge conflicts, but only if I know I'm not doing this for nothing.

2016-10-02 15:18 UTC, miigotu requested changes
Conflict is in **init**. Some trivial changes I mentioned below but overall it looks great.
I only mentioned the change suggested by https://www.quantifiedcode.com/app/project/gh:SickRage:SickRage/diff/422fe8ae30eed0bc4c7feedefd5f666011d69440/527225365b9843e38cea2fc0d7138880192af257/issues

2016-10-02 15:18 UTC, miigotu commented on sickbeard/providers/filelist.py
> +                    if len(torrent_rows) < 1:
`if not torrent_rows:`

2016-10-02 15:18 UTC, miigotu commented on sickbeard/providers/filelist.py
> +            logger.log("Search Mode: {}".format(mode), logger.DEBUG)
`logger.log("Search Mode: {0}".format(mode), logger.DEBUG)`

2016-10-02 15:18 UTC, miigotu commented on sickbeard/providers/filelist.py
> +                                               " minimum seeders or leechers: {} (S:{} L:{})".format
`" minimum seeders or leechers: {0} (S:{1} L:{2})".format`

2016-10-02 15:18 UTC, miigotu commented on sickbeard/providers/filelist.py
> +                                logger.log("Found result: {} with {} seeders and {} leechers".format
`logger.log("Found result: {0} with {1} seeders and {2} leechers".format`

2016-10-02 22:56 UTC, ovidiub13 commented on sickbeard/providers/filelist.py
> +            logger.log("Search Mode: {}".format(mode), logger.DEBUG)
Added.

2016-10-02 22:56 UTC, ovidiub13 commented on sickbeard/providers/filelist.py
> +                    if len(torrent_rows) < 1:
Added.

2016-10-02 22:56 UTC, ovidiub13 commented on sickbeard/providers/filelist.py
> +                                               " minimum seeders or leechers: {} (S:{} L:{})".format
Added.

2016-10-02 22:56 UTC, ovidiub13 commented on sickbeard/providers/filelist.py
> +                                logger.log("Found result: {} with {} seeders and {} leechers".format
Added.

2016-10-02 23:01 UTC, ovidiub13 commented
I see code coverage has decreased. Can I make some kind of test for this patch?
How would I make that?

2016-10-03 00:28 UTC, miigotu commented
Dont worry about the coverage, coveralls doesnt properly detect our provider tests for 2 reasons: 1, the proivders are lazy loaded and 2. One test suite tests all providers.

2016-10-03 00:28 UTC, miigotu approved these changes

2016-10-03 00:29 UTC, merged