Tagger resolution improvements
SickChill/sickchill pull request #2431
Opened 2016-10-04 07:11 UTC by snamds

Proposed changes in this pull request:
- Allow tags lists in tags.py
- Added "resolution" regex item that captures "hd 720" (without p)
- Modified newpct provider to treat "hd 720" as "hd 720p x264"

2016-10-04 07:11 UTC, SickRage2 commented
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

2016-10-19 08:03 UTC, miigotu requested changes
We have to be extra careful changing the tagger, my suggestions should help keep it reliable.

2016-10-19 08:03 UTC, miigotu commented on sickrage/recompiled/tags.py
> +    re.compile(r'([sph]d)(.?tv)?.?( )*(?P<vres>4320|2160|1080|720|480|360)(?P<scan>[pi])?', re.I)
Should not capture extra groups if it can be avoided, also it should make sure the vres is followed by a non digit in cases where scan is missing to prevent false matches as much as possible
```python
re.compile(r'(:?[sph]d)(:?.?tv)?[ .]*(?P<vres>4320|2160|1080|720|480|360)(?P<scan>[pi])?[^\d]', re.I)
```

2016-10-19 08:03 UTC, miigotu commented on sickrage/tagger/episode.py
> +        return '' if not match or not match.group('scan') else match.group('scan').lower()
```python
return ('', match.group('scan').lower())[bool(match and match.group('scan'))]
```

2016-10-20 14:42 UTC, snamds commented on sickrage/tagger/episode.py
> +        return '' if not match or not match.group('scan') else match.group('scan').lower()
This wouldn't work. The tuple can't be created because "match.group('scan')" is None. ".lower()" of Nonetype raises an exception

2016-10-20 17:21 UTC, miigotu commented on sickrage/tagger/episode.py
> +        return '' if not match or not match.group('scan') else match.group('scan').lower()
doh, ur right. I just dont like the double `not`...

``` python
return match.group('scan').lower() if match and match.group('scan') else ''
```

2016-10-20 19:12 UTC, merged