Newpct hdtv by url
SickChill/sickchill pull request #2524
Opened 2016-10-23 11:45 UTC by snamds

Newpct people are not consistent with the 720p tags. This update detect hdtv 720p releases using the download url

2016-10-23 11:45 UTC, SickRage2 commented
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

2016-10-23 12:12 UTC, miigotu requested changes

2016-10-23 12:12 UTC, miigotu commented on sickbeard/providers/newpct.py
> +        title = re.sub(r'( ){2,}', ' ', title, flags=re.I)
```python
title = re.sub(r'[ ]{2,}', ' ', title, flags=re.I)
```

2016-10-23 12:12 UTC, miigotu commented on sickbeard/providers/newpct.py
> +                title += ' 720p HDTV x264'
What about 1080p?
Also what if the title is something like 
`Arrow - Temporada 4 [HDTV][Cap.423][Español Castellano]` and the url is `http://www.newpct.com/descargar-seriehd/Arrow/capitulo-423/hdtv-720p-ac3-5-1/`? You end up with HDTV in the title 2x

2016-10-25 09:31 UTC, miigotu approved these changes

2016-10-25 09:43 UTC, merged