Add home split options
SickChill/sickchill pull request #2596
Opened 2016-11-06 17:52 UTC by beschoenen

Add split options to the home screen.

![image](https://cloud.githubusercontent.com/assets/1887585/20040120/f80293ac-a451-11e6-8ffd-d37f57de3b3c.png)

![image](https://cloud.githubusercontent.com/assets/1887585/20040124/0097bf92-a452-11e6-8a37-33d501178cfb.png)

Current options are: None, Anime, Sports, Anime & Sports, Root dir.

2016-11-06 17:52 UTC, SickRage2 commented
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

2016-11-06 17:57 UTC, beschoenen commented
@miigotu Should this new setting be saved in the `config.ini`?

2016-11-06 18:19 UTC, miigotu commented
Cant just select one root dir anymore? Point of that is the shows for one user (wife/kids/etc) can be put in their own root and use that option to filter which user's shows are displayed.

2017-01-01 17:54 UTC, beschoenen commented
![image](https://cloud.githubusercontent.com/assets/1887585/21582337/a1c2a378-d053-11e6-8fe0-086697ba7601.png)

![image](https://cloud.githubusercontent.com/assets/1887585/21582340/b8b6c80c-d053-11e6-986d-d2878318fcb5.png)

2017-01-01 18:02 UTC, beschoenen commented
@miigotu I think I'm missing something, `home_view` doesn't get saved to the `config.ini`.

2017-01-01 21:51 UTC, miigotu requested changes

2017-01-01 21:51 UTC, miigotu commented on sickbeard/__init__.py
> +        HOME_VIEW = check_setting_int(CFG, 'GUI', 'home_view', None)
```python
HOME_VIEW = check_setting_str(CFG, 'GUI', 'home_view', None)
```

2017-01-01 21:51 UTC, miigotu commented on sickbeard/__init__.py
> +        HOME_VIEW = check_setting_int(CFG, 'GUI', 'home_view', None)
To fix saving to config, around https://github.com/SickRage/SickRage/pull/2596/files#diff-ca8b2565f5e99e9c38ee2c2a4a56b64fR2236 add 
```python
'home_view': HOME_VIEW
```

2017-01-01 21:51 UTC, miigotu commented on sickbeard/__init__.py
> +        HOME_VIEW = check_setting_int(CFG, 'GUI', 'home_view', None)
Er, Line 2236 -ish, it wont let me comment there

2017-01-01 22:06 UTC, miigotu commented
Maybe needs a way to toggle or collapse individual roots? I like being able to select just one root dir to view at a time with 2 clicks atm

2017-01-01 22:21 UTC, beschoenen commented
Maybe a little arrow before the path of a root directory? (so only when split by root directory)

2017-01-01 22:30 UTC, miigotu commented
maybe. I think you could also leave the  drop down how I have it atm and have that collapse or hide all other roots so only one is showing. Another cool option would be to have root dir "groups" that you can label what you want and add a few root dirs to.

Like
`Kids` = `/RAID1/Videos/Kids_Shows`, `/RAID1/Videos/Christmas`
`Mommy` = `/RAID1/Videos/Shows`, `/RAID1/Videos/Christmas`

Ofc it would be handled by a string of numbers:
```
[General]
ROOT_DIRS = 1|/RAID1/Videos/Kids_Shows,2|/RAID1/Videos/Christmas,3|/RAID1/Videos/Shows,4|/RAID1/Videos/Shows/Anime,5|/RAID1/Videos/Documentaries
[Root_Groups]
Mommy = 23
Kids = 12
Dad = 345
```

That would get us started down the road of being able to split up SR by user I think

2017-01-02 16:34 UTC, beschoenen commented
That's a nice idea, but wouldn't it be better to do that in another PR?

2017-03-13 10:55 UTC, closed without merging