Feature: Selective history logs removal
SickChill/sickchill pull request #3138
Opened 2017-02-13 12:30 UTC by sharkykh

# Selective history logs removal
### Allows the user to selectively remove logs from the database, as opposed to clear the whole log, and trimming from 30 days and up. Includes a 'confirm' dialog.

![image](https://cloud.githubusercontent.com/assets/10238474/22883064/fd8b5334-f1f6-11e6-95f2-1f49aa916513.png)

**Each checkbox gets a 'unique' ID in order to find it in the database's 'history' table.
The ID is a combination of date+showid+season+episode.**

It's very useful to me (I like to keep my history neat), perhaps it's useful to other people.

2017-02-13 12:30 UTC, SickRage2 commented
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

2017-02-14 05:38 UTC, miigotu commented
Don't have time to review this completely, but can you move the history.js code into core.js in the proper section?  All js is being worked into core.js

2017-02-14 08:32 UTC, sharkykh commented
Moved and tested again.

2017-02-14 08:40 UTC, miigotu commented
One more thing, spaces not tabs. If you want to fix that you can, or I can fix it after merge. I'll test it tomorrow

2017-02-14 08:50 UTC, OmgImAlexis requested changes

2017-02-14 08:50 UTC, OmgImAlexis commented on gui/slick/js/core.js
> +                        removeCount++; }
This should be on the next line. You should really look at how the rest of the code is within the files.

2017-02-14 08:50 UTC, OmgImAlexis commented on gui/slick/js/core.js
> +                if(removeCount < 1) { return false; }
```
if(removeCount) {
    return false;
}
```

2017-02-14 08:50 UTC, OmgImAlexis commented on gui/slick/js/core.js
> +                        var params = 'toRemove='+removeArr.join('|');
`'toRemove=' + removeArr.join('|');`
Notice the space.

2017-02-14 08:50 UTC, OmgImAlexis commented on gui/slick/js/core.js
> +                        if(this === check || this === lastCheck) { found++; }
Same here.

2017-02-14 08:50 UTC, OmgImAlexis commented on gui/slick/js/core.js
> +                            case 1: if(!this.disabled) { this.checked = lastCheck.checked; }
This should be inside of a function if it's inline with a case.

Really instead of a case you should just be using an if for the whole thing.

2017-02-14 08:51 UTC, OmgImAlexis commented
@sharkykh when you open a PR you should really be following the coding style within the files and project instead of using whatever you normally use as others will need to see it.

2017-02-14 09:18 UTC, miigotu commented
Play nice, this is one of this users forts PR here =p
Thanks for the review @OmgImAlexis, and thanks for the PR too @sharkykh

2017-02-14 09:40 UTC, sharkykh commented on gui/slick/js/core.js
> +                            case 1: if(!this.disabled) { this.checked = lastCheck.checked; }
This is actually not my code.
I confess, this is copied from [gui/slick/js/massUpdate.js#L87-L107](https://github.com/SickRage/SickRage/blob/develop/gui/slick/js/massUpdate.js#L87-L107)
and trimmed down for one checkbox class.
The same goes for line 2980 (see [massUpdate.js#74](https://github.com/SickRage/SickRage/blob/develop/gui/slick/js/massUpdate.js#L74)),
and 3005, ovbiously..

Anyway, you are right, so I'll change in my PR.

2017-02-14 09:41 UTC, sharkykh commented
@miigotu : Yes, I know... looks like I missed them. Done.

@OmgImAlexis : _**Thank you, I appreciate your comment and review.**_
It _**was**_ my intention to continue the coding style currently in the files.
I guess I wasn't paying enough attention.

I'll push another commit in a couple of minutes.

2017-02-14 21:43 UTC, merged