A workaround for #1377
SickChill/sickchill pull request #3178
Opened 2017-02-19 15:10 UTC by sharkykh

A workaround for #1377

When trying to use an episode naming pattern in the following scenario:

- **Pattern:** `Season %S/%SN - Season %S, Episode %E - %EN/%RN` (_notice there are two directories_)
- **Custom Anime Naming:** Selected (_otherwise known as NAMING_CUSTOM_ANIME=1_)
- **Anime Absolute Number:** [Add/Only](https://cloud.githubusercontent.com/assets/10238474/23103252/e149c0f6-f6c0-11e6-8d7b-1a01c4051dfe.png) (_otherwise known as anime_type=1 or anime_type=2_)

You would get
`Season 2/Show Name - 003 - Ep Name/Show.Name.S02E03.HDTV.XviD-RLSGROUP.ext`
**for a normal (non-anime) episode**,
instead of
`Season 2/Show Name - S02E03 - Ep Name/Show.Name.S02E03.HDTV.XviD-RLSGROUP.ext`

This is a 'hacky' fix, a workaround for this problem.
Any suggestions for a better one are welcome.

2017-02-19 15:10 UTC, SickRage2 commented
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

2017-02-19 18:36 UTC, sharkykh commented
Let me see if I understand you correctly... https://github.com/sharkykh/SickRage/commit/68903347b3414999ee23c74adc874e603c1733d5 (this is based of clean develop again)

Result:
Worked for testing at the Episode Naming config,
but failed in Preview Rename of a show.

2017-02-19 18:45 UTC, h3llrais3r commented
You're right. I'm checking the preview rename now...

2017-02-19 19:04 UTC, h3llrais3r commented
Replace https://github.com/SickRage/SickRage/pull/3178/files#diff-28cfafa47039ed0a3b3f6be8687d0811R2368 by the line below and it should be fine now.
``
result = ek(os.path.join, self.formatted_dir(anime_type=anime_type), result)
``

2017-02-19 19:04 UTC, h3llrais3r requested changes
> Let me see if I understand you correctly... sharkykh@6890334 (this is based off a clean develop again)

Replace https://github.com/sharkykh/SickRage/blob/develop/sickbeard/tv.py#L2368 by the line below and it should be fine now.
``
result = ek(os.path.join, self.formatted_dir(anime_type=anime_type), result)
``

2017-02-19 19:04 UTC, h3llrais3r commented on sickbeard/tv.py
> -            return self._format_pattern(os.sep.join(name_groups[:-1]), multi)
I think this line should not be changed.
Instead, the anime_type should also be added here:
https://github.com/sharkykh/SickRage/blob/develop/sickbeard/naming.py#L208

Can you try again with these changes?
By doing it this way, we only pass the anime_type to the formatted_dir function and it seems to give the correct results.

@miigotu what do you think?

2017-02-19 19:40 UTC, sharkykh commented on sickbeard/tv.py
> -            return self._format_pattern(os.sep.join(name_groups[:-1]), multi)
Just checked, it works perfectly.
Updated the PR.
Thanks @h3llrais3r :)

2017-02-19 19:41 UTC, h3llrais3r approved these changes

2017-02-19 19:41 UTC, h3llrais3r commented
@miigotu Can you do a final review?

2017-02-19 19:48 UTC, h3llrais3r commented on sickbeard/tv.py
> -            return self._format_pattern(os.sep.join(name_groups[:-1]), multi)
Thanks for the PR 😄

2017-02-20 01:51 UTC, miigotu commented
Fine with me =P
Approved

2017-02-20 01:55 UTC, merged