Fix delete associated files on rename
SickChill/sickchill pull request #3343
Opened 2017-03-06 19:55 UTC by h3llrais3r

When the 'move associated files' flag is not enabled, the 'delete non associated files' flag is enabled, and there are associated files extensions, the associated files are still deleted when renaming. This fixes this behaviour.

Fix for https://github.com/SickRage/SickRage/issues/3306

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

2017-03-06 19:55 UTC, SickRage2 commented
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

2017-03-06 20:38 UTC, miigotu commented
I think there is a better solution.
If the file is in the show folder, ALL files are to be kept.
`if some_show_path in associated_file_path or sickbeard.MOVE_ASSOCIATED_FILES and associated_file_path.endswith(tuple(sickbeard.ALLOWED_EXTENSIONS.split(","))):`

2017-03-06 21:02 UTC, h3llrais3r commented
I think this is a point of discussion. 😉 
I rather have my library clean and similar.
If I only list 'srt' in my 'associated files extensions' I only want them, also after a rename.
If for some kind of reason other file extensions are still there, I want them removed so I have a clean library. 😉

2017-03-06 21:32 UTC, h3llrais3r commented
In fact an even better way would be not to check the associated files during rename and just rename everything that matches the filename of the video.

2017-03-07 01:28 UTC, miigotu commented
You could add an extra param to list_associated_files that lets us know this is an in-showdir listing, to avoid deleting files from the tv show dir

2017-03-07 07:05 UTC, h3llrais3r commented
I had the same idea. Will have a look this evening.

2017-03-07 18:29 UTC, h3llrais3r commented
@miigotu Do we keep the same logic for the rename also?
I mean, what do we do with https://github.com/SickRage/SickRage/blob/develop/sickbeard/postProcessor.py#L207-L213?
Do we keep those 2 excludes?

2017-03-07 19:57 UTC, h3llrais3r commented
@miigotu Please review.
I added the parameter for rename and also fixed the rename of subtitles in a separate subtitle dir. 😉

2017-03-07 20:05 UTC, sharkykh commented on sickbeard/postProcessor.py
> +                    # always allow during renaming
I think this can be done a bit simpler:
```python
if rename or sickbeard.MOVE_ASSOCIATED_FILES and associated_file_path.endswith(tuple(sickbeard.ALLOWED_EXTENSIONS.split(","))):
    if sickbeard.MOVE_ASSOCIATED_FILES and is_allowed_extension:
        file_path_list_to_allow.append(associated_file_path)
    elif sickbeard.DELETE_NON_ASSOCIATED_FILES and not is_allowed_extension:
        file_path_list_to_delete.append(associated_file_path)
```

Correct me if I'm wrong...

2017-03-07 20:10 UTC, sharkykh commented on sickbeard/postProcessor.py
> +                    # always allow during renaming
(I corrected my code)

2017-03-07 20:16 UTC, h3llrais3r commented on sickbeard/postProcessor.py
> +                    # always allow during renaming
I rather keep it separated (and a matter of taste). 😄 
Additionally, with my code, you don't need to execute the logic for `is_allowed_extension` when we are renaming...

2017-03-07 20:27 UTC, sharkykh commented on sickbeard/postProcessor.py
> +                    # always allow during renaming
> Additionally, with my code, you don't need to execute the logic for is_allowed_extension when we are renaming...

Actually,
Python evaluates [statements from left to right](http://stackoverflow.com/questions/752373/is-it-safe-to-rely-on-condition-evaluation-order-in-if-statements) (sorry I couldn't find the Python docs refrence),
so when `rename == True`, it will immediately jump inside (doesn't check anything after the `or`) 

------

>I rather keep it separated (it's a matter of taste). 😄 

:+1: miigotu will decide :wink:

2017-03-07 20:58 UTC, h3llrais3r commented on sickbeard/postProcessor.py
> +                    # always allow during renaming
`is_allowed_extension` is set before the if statement, so it's always executed 😉

2017-03-07 21:04 UTC, sharkykh commented on sickbeard/postProcessor.py
> +                    # always allow during renaming
Sorry I wasn't clear in my review.

My proposal is to change this section:
```python
# Define associated files (all, allowed and non allowed)
if ek(os.path.isfile, associated_file_path):
    if rename:
        # always allow during renaming
        file_path_list_to_allow.append(associated_file_path)
    else:
        # check if allowed or not during post processing
        is_allowed_extension = associated_file_path.endswith(tuple(sickbeard.ALLOWED_EXTENSIONS.split(",")))
        if sickbeard.MOVE_ASSOCIATED_FILES and is_allowed_extension:
            file_path_list_to_allow.append(associated_file_path)
        elif sickbeard.DELETE_NON_ASSOCIATED_FILES and not is_allowed_extension:
            file_path_list_to_delete.append(associated_file_path)
```

to this:
```python
# Define associated files (all, allowed and non allowed)
if ek(os.path.isfile, associated_file_path):
    if rename or sickbeard.MOVE_ASSOCIATED_FILES and associated_file_path.endswith(tuple(sickbeard.ALLOWED_EXTENSIONS.split(","))):
        file_path_list_to_allow.append(associated_file_path)
    elif sickbeard.DELETE_NON_ASSOCIATED_FILES and not is_allowed_extension:
        file_path_list_to_delete.append(associated_file_path)
```

2017-03-07 21:07 UTC, sharkykh commented on sickbeard/postProcessor.py
> +                    # always allow during renaming
Now it's irrelevant haha

2017-03-07 21:08 UTC, miigotu requested changes

2017-03-07 21:08 UTC, miigotu commented on sickbeard/postProcessor.py
> +                elif sickbeard.DELETE_NON_ASSOCIATED_FILES and not is_allowed_extension:
This idea to only delete files that are not in the allowed extension list doesnt sit well with me.
Either files are in the file_path_list_to_allow (when MOVE_ASSOCIATED_FILES and they are in the allow list) or they are to be deleted when DELETE_NON_ASSOCIATED_FILES.
Once it makes it past the first if and DELETE_NON_ASSOCIATED_FILES then ALL should be deleted, whether they are associated or not.

In other words, all files must be in one of the 2 lists, none can be orphaned out and not deleted or moved.

2017-03-07 21:34 UTC, h3llrais3r commented
Updated.

2017-03-07 21:36 UTC, merged