Add --force-update argument
SickChill/sickchill pull request #3591
Opened 2017-04-03 20:41 UTC by sharkykh

Add `--force-update` start argument that forces SickRage to update by downloading the master-tarball from Github.
This will help resolve issues when SickRage doesn't load because of a breaking commit.

This is intended for users that installed using source install.

2017-04-04 01:27 UTC, miigotu requested changes

2017-04-04 01:27 UTC, miigotu commented on SickBeard.py
> +                print('See https://github.com/SickRage/SickRage/wiki/FAQ\'s-and-Fixes#update-problems-try-this')
We also support updating with a "source" install, which is a downloaded zip from github that is extracted into PROG_DIR.

You are calling the SourceUpdateManager here instead of the GitUpdateManager.

```python
            self.install_type = self.find_install_type()
            if self.install_type == 'git':
                self.updater = GitUpdateManager()
            elif self.install_type == 'source':
                self.updater = SourceUpdateManager()
```

2017-04-04 01:31 UTC, sharkykh commented on SickBeard.py
> +                print('See https://github.com/SickRage/SickRage/wiki/FAQ\'s-and-Fixes#update-problems-try-this')
I know. But I think many of the stuff GitUpdateManager() needs to update is not initialized so early into the code.

I didn't want to add a messy code to SickBeard.py, so I compromised on this being a solution for Source installations only.

2017-04-04 01:32 UTC, sharkykh commented on SickBeard.py
> +                print('See https://github.com/SickRage/SickRage/wiki/FAQ\'s-and-Fixes#update-problems-try-this')
> We also support updating with a "source" install, which is a downloaded zip from github that is extracted into PROG_DIR.

If you hadn't noticed, I **am** using SourceUpdateManager.
It's GitUpdateManager that I'm not using.

2017-04-04 01:47 UTC, miigotu commented on SickBeard.py
> +                print('See https://github.com/SickRage/SickRage/wiki/FAQ\'s-and-Fixes#update-problems-try-this')
Git updates shouldnt require anything other than git reset --hard and git pull.  The repo info is held in the .git/config anyways so git handles that all externally.

Its like 
```python
gh =  Github(sickbeard.PROG_DIR)
gh.reset()
gh.pull()
```
or something like that lol

2017-04-04 15:29 UTC, sharkykh commented on SickBeard.py
> +                print('See https://github.com/SickRage/SickRage/wiki/FAQ\'s-and-Fixes#update-problems-try-this')
I didn't go into the code again just yet,
but I don't understand - you still think GitUpdateManager would work?
It seemed to me like it uses config vars and Github to do all kinds of funky stuff.

**Or** do you think it's better to just use git commands in `SickBeard.py`..?

2017-04-04 15:31 UTC, miigotu commented on SickBeard.py
> +                print('See https://github.com/SickRage/SickRage/wiki/FAQ\'s-and-Fixes#update-problems-try-this')
Git commands will work just fine. force a reset/clean and pull and restart

2017-04-04 15:32 UTC, sharkykh commented on SickBeard.py
> +                print('See https://github.com/SickRage/SickRage/wiki/FAQ\'s-and-Fixes#update-problems-try-this')
I'll look into that. Sounds like a bitch to test this though.

2017-04-04 16:58 UTC, sharkykh commented
Not sure if this is sufficient. It's isn't fully tested yet.

2017-04-06 09:10 UTC, sharkykh commented
I just tested and it works 😄

2017-04-07 06:32 UTC, merged