Fix error when adding show with invalid tvdbid
SickChill/sickchill pull request #3598
Opened 2017-04-04 19:37 UTC by h3llrais3r

Fixes https://github.com/SickRage/SickRage/issues/3379

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

2017-04-04 19:49 UTC, sharkykh approved these changes
Same solution as implemented in Trending shows.

2017-04-04 19:50 UTC, sharkykh commented
Maybe also run grunt and push it here.

2017-04-04 19:56 UTC, sharkykh requested changes

2017-04-04 19:56 UTC, sharkykh commented on sickbeard/helpers.py
> +            return None
This is indented too much (remove 4 spaces from all 3 lines)

2017-04-05 05:09 UTC, h3llrais3r commented on sickbeard/helpers.py
> +            return None
Will do this evening.

2017-04-05 05:10 UTC, h3llrais3r commented
Why running grunt? 
I thought @miigotu does this when merging into master only?

2017-04-05 13:31 UTC, sharkykh commented
He uses an automated script we built together and it doesn't run grunt...
So I'm not sure.

2017-04-05 16:14 UTC, sharkykh approved these changes

2017-04-05 16:15 UTC, h3llrais3r commented
Ok, but shouldn't you run the script before merging into master only?

2017-04-05 16:25 UTC, sharkykh commented
**If you push grunt here,** it gets merged into develop and then it's always ready to be merged to master. It's also cleaner this way, IMO, because pull requests are squashed into a single commit.

Because only miigotu can commit straight it to develop,
and like I said, the script miigotu uses doesn't do the grunt task just yet (because of reasons),
I think it's better to run grunt and push it to the PR before merging it.

**Also, think about this:**
Some people use develop but don't have developer enabled (granted, not many).
So when you push core.js without core.min.js,
core.min.js is still the old version, and that can cause issues.

2017-04-05 16:31 UTC, sharkykh commented
Only downside I can think of is it would create a merge conflict on core.min.js,
when you click "Update branch" on another PR that edits core.js.

2017-04-05 16:32 UTC, h3llrais3r commented
That's what I also thought 😄 
But I think we can't ask everyone to run the grunt script when creating PR's?

2017-04-05 16:36 UTC, sharkykh commented
I agree that it should be automated.
I'm working on [automatically updating the translations](https://github.com/SickRage/SickRage/pull/3557) first (on a push to master).
If that proves to be a good solution we'll make sure to run grunt too.

2017-04-07 20:13 UTC, h3llrais3r commented
@sharkykh @miigotu Can we merge?
@sharkykh @miigotu Can we merge?

2017-04-07 20:13 UTC, h3llrais3r commented
@sharkykh @miigotu Can we merge?

2017-04-07 20:16 UTC, sharkykh commented
I have approved already :)

2017-04-08 17:36 UTC, sharkykh commented on sickbeard/webserve.py
> +
I just had a chance to actually test it,
and because it tried to add the show even when it didn't find it on TheTVDB,
some errors were logged, and a traceback was printed...

2017-04-11 18:17 UTC, h3llrais3r commented on sickbeard/webserve.py
> +
Ok for me.

2017-04-11 18:20 UTC, h3llrais3r commented on sickbeard/webserve.py
> +
Can you merge?

2017-04-11 18:56 UTC, merged

2017-04-14 18:32 UTC, sharkykh commented
@h3llrais3r 
>That's what I also thought :smile:
But I think we can't ask everyone to run the grunt script when creating PR's?

https://github.com/SickRage/SickRage/commit/1d28b358576b35b101bb0f662858ae5296d2ef8b