Schedule now shows newly snatched episodes (#3600)
SickChill/sickchill pull request #3616
Opened 2017-04-10 13:42 UTC by chris-gh

Fixes #3600

Proposed changes in this pull request:
- Schedule screen now shows "snatched" episodes
- Snatched episodes will only be displayed if they are new (location is empty) - ie. new snatches not update quality snatches
- Snatches will be removed once server updates status to download
- This uses the "Missed episodes range" setting to tell list how far back to find snatched episodes

This feature will hopefully easily identify any episodes that have been snatched and have failed or are currently in progress.

Apologies in advance for any code issues, it's my first time using python.

2017-04-10 18:09 UTC, miigotu commented
@sharkykh see any problems with this?

2017-04-10 20:37 UTC, sharkykh commented
I'll take a closer look later today or tomorrow.

2017-04-11 06:34 UTC, sharkykh commented
Right from the get-go:
I snatched an episode through the schedule screen, and now `gui/slick/js/ajaxEpSearch.js` keeps removing it from the list whenever I refresh.

2017-04-11 07:55 UTC, sharkykh requested changes
1. My comment about `gui/slick/js/ajaxEpSearch.js` still stands.
Need to make sure it only affects the Schedule view.
2. @miigotu [What about the API?](https://github.com/SickRage/SickRage/blob/599431d9c5a99ad57512c2e84c54ff15bb493a88/sickbeard/webapi.py#L709-L726)

2017-04-11 07:55 UTC, sharkykh commented on sickrage/show/ComingEpisodes.py
> +                category = 'snatched'
I'd prefer:
```python
if int(result[b'epstatus']) in Quality.SNATCHED + Quality.SNATCHED_PROPER + Quality.SNATCHED_BEST:
    if not result[b'location']:
        category = 'snatched'
    else:
        continue
```
This is one less `elif` and looks nicer IMO.

2017-04-11 07:55 UTC, sharkykh commented on gui/slick/views/schedule.mako
> +                                        show_div = 'listing-snatched'
Same as above,
```python
if int(cur_result[b'epstatus']) in Quality.SNATCHED + Quality.SNATCHED_PROPER + Quality.SNATCHED_BEST:
    if not cur_result[b'location']:
        show_div = 'listing-snatched'
    else:
        continue
```

----

You can even go simpler:
```python
if not cur_result[b'location'] and int(cur_result[b'epstatus']) in Quality.SNATCHED + Quality.SNATCHED_PROPER + Quality.SNATCHED_BEST:
    show_div = 'listing-snatched'
```
However that might be a little bit slower, but I'm not too sure about that.

2017-04-11 07:55 UTC, sharkykh commented on gui/slick/views/schedule.mako
> +                                        % if cur_result[b'location'] and int(cur_result[b'epstatus']) in Quality.SNATCHED + Quality.SNATCHED_PROPER + Quality.SNATCHED_BEST:
Calendar view doesn't use the "listing-keys".
Instead we should just ignore all snatched episodes.
```python
% if int(cur_result[b'epstatus']) in Quality.SNATCHED + Quality.SNATCHED_PROPER + Quality.SNATCHED_BEST:
```

2017-04-11 07:55 UTC, sharkykh commented on gui/slick/views/schedule.mako
> +                                <h2 class="day">${_('Missed')} / ${_('Snatched')}</h2>
I'm unable to test this...

And...
I'm not saying this is wrong, only odd - 
shouldn't "Snatched" get its own segment?

2017-04-11 08:24 UTC, chris-gh commented
I'll have a look at some of those code style changes later tonight and respond to the other queries.

From a quick look the ajax is only affecting schedule (as that's the only one with a id=forceUpdate attribute).

But this was just checked using github viewer, I'll have better access to the files once I'm home from work.

2017-04-11 13:52 UTC, chris-gh commented
I've made the code style changes as suggested above.

Also while looking into the `ajaxEpSearch.js` I found a bug that was that pre-existing before my change. For Banner/Poster views, it was finding the wrong `tr` and removing half the panel and not the full row, as those views have multiple `tr` elements per episode.

With the Missing / Snatched category part, that's a bit trickier when sorting by date. I had a look in to it and the problem with it is that episodes will be intermixed with different statuses. This also fails when a snatched episode is "today" as it will show under that category rather than snatched/missing.

The best thing I can think of is to alter the date sorting to be:
* Sort by snatched = true first
* Then sort by date

```
sorts = {
        'date': (lambda a, b: a[b'localtime'] < b[b'localtime']),
        'network': (lambda a, b: (a[b'network'], a[b'localtime']) < (b[b'network'], b[b'localtime'])),
        'show': (lambda a, b: (a[b'show_name'], a[b'localtime']) < (b[b'show_name'], b[b'localtime'])),
    }
```
That way all the snatched will be in the top panel (even if it's today's date), then missing will show in the second panel, then today, then days of week, then later.

The logic in that part of `schedule.mako` for panel + date sorting is a bit confusing so probably will need to be cleaned up a bit to use a variable containing each header type as it goes through rather than individual bool flags per type .

2017-04-13 01:48 UTC, sharkykh commented
I'll test/review it again soon.

If you feel like doing a code clean up in `schedule.mako`, then go for it.

2017-04-13 02:41 UTC, chris-gh commented
I think once i get the sorting / rewrite of the grouping it should be ready to push in.

Main issue is it's my first time using python so need to get my head around how lambdas and the sorting works in it.

If you're able to give me a pointer on how to change this:

`'date': (lambda a, b: a[b'localtime'] < b[b'localtime']),`

To sort by `statusid = snatched`, then by `localtime`, that will be a massive help.

Then the change to `schedule.mako` should be fairly simple for me to implement.

2017-04-22 05:02 UTC, sharkykh submitted a review, later dismissed

2017-04-22 05:43 UTC, sharkykh commented
I now think that when you actually snatch an episode it should move it to the "Snatched" segment/section.
But I'm still not in the right mood for it.

2017-04-22 06:43 UTC, chris-gh commented
Not sure that items should move sections. If you take all the other snatch actions (show screens, etc), they all just stay inline and change colour - so this is just following the same process until page is manually refreshed.

There is one last change that needs to be done for this feature to be complete, and that's the sorting for poster date view (as mentioned above). The snatched episodes need to be listed first and then the rest sorted by date order after that. Currently if there are inter-twined missing/snatched the headers will show up multiple times.

@sharkykh - Are you able to help with that one last bit?

2017-04-22 07:07 UTC, sharkykh commented
Can you check again? I can't seem to be able to reproduce this issue.

2017-04-22 07:23 UTC, chris-gh commented
![example-poster-datesorting2](https://cloud.githubusercontent.com/assets/1967906/25302357/ce4826d8-277f-11e7-8294-29f91251f99c.png)

Yep - still doing it. The fix it to somehow change:

```
sorts = {
        'date': (lambda a, b: a[b'localtime'] < b[b'localtime']),
        'network': (lambda a, b: (a[b'network'], a[b'localtime']) < (b[b'network'], b[b'localtime'])),
        'show': (lambda a, b: (a[b'show_name'], a[b'localtime']) < (b[b'show_name'], b[b'localtime'])),
    }
```
to:
```
        'date': (lambda a, b: (a[b'epstatus'] in Snatched[] ? 0 : 1, a[b'localtime']) < (b[b'epstatus'] in Snatched[] ? 0 : 1, b[b'localtime'])),
```

Does that make sense?

2017-04-22 07:41 UTC, sharkykh commented
OK, now I'm able to reproduce (after removing some episodes from my database..)
I'll try and make it work.

2017-04-28 17:44 UTC, sharkykh commented
@chris-gh I haven't had much luck so far...

2017-04-30 09:33 UTC, chris-gh commented
@sharkykh just went to have another go at this myself and from the looks of it, the lambda sorting is not working at all.

I switched back to the master branch and scheduled poster view is always sorting by airdate, no matter what.

This would have been why I couldn't get mine working - I made assumption that the sorting code was working.

There is the following code:
```
        results.sort(key=itemgetter(b'localtime'))
        results.sort(ComingEpisodes.sorts[sort])
```
From the looks, the top sort is working by sorting airdate (for all cases), and then the second re-sort does nothing.

I'll have a look into the second sorting part and see if I can work it out - once that's done I'm guessing it'll just be a simple case of adding the second (snatched) sort field in and it'll work.

2017-04-30 10:03 UTC, chris-gh commented
Fixed it - went back through old versions of the file and found that it previously was using cmp() in the lambda statements which sorted correctly. I've put that through in a separate commit (7491297).

With the final commit (4f43760) I think this issue is now complete and ready to go back in, once it's had a final review.

2017-04-30 10:31 UTC, sharkykh commented
@chris-gh 
Tried that now. It works well for me.

2017-04-30 10:58 UTC, sharkykh commented
@chris-gh Your code gave me an idea. Please test my latest commit.
It's a cleaner and more readable code. Used itemgetter and `key=` instead of `cmp` which is an old technique.
I **can't** confirm that it keeps the snatched and missed together.
If they mash together, it's easy to add more comparisons. (I commented out the other solution)

2017-04-30 11:04 UTC, chris-gh commented
Can confirm your new way of sorting worked.

Just need to re-add my code back in. Would you like me to do that?

2017-04-30 11:06 UTC, sharkykh commented
@chris-gh I'll do that, I have some more small changes.
You mean we still need to sort using 'snatchedsort`, correct?

2017-04-30 11:09 UTC, chris-gh commented
Yes, still need to sort by snatchedsort. 

By uncommenting locally the 2 lines including snatched sort (the sorter and the setter) everything is working 100% from my testing.

2017-04-30 11:19 UTC, sharkykh approved these changes

2017-04-30 11:19 UTC, sharkykh commented
I can confirm that this is indeed working as expected now :smile: 

@miigotu Any notes on this before I merge?

2017-04-30 11:44 UTC, sharkykh commented
@chris-gh 
Doesn't look so good on my phone (Galaxy S5).
<table>
<thead>
<td><b>Before</b></td>
<td><b>After</b></td>
</thead>
<tr>
<td><img src="https://cloud.githubusercontent.com/assets/10238474/25564081/1072bae4-2db3-11e7-9b26-e34bc7581350.png" /></td>
<td><img src="https://cloud.githubusercontent.com/assets/10238474/25564085/21fb37be-2db3-11e7-88a9-259df8f4322d.png" /></td>
</tr>
</table>

I'll try to fix this but I don't remember web design that well.

2017-05-01 05:40 UTC, merged