Add maximum size
SickChill/sickchill pull request #3655
Opened 2017-04-24 17:53 UTC by ArthurGarnier

Fixes : http://feathub.com/SickRage/SickRage/+77

Proposed changes in this pull request:
- Add field in "edit show" to set a maximum size in MB
- Default value is -1, means ignore the parameter

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

2017-04-24 18:16 UTC, OmgImAlexis commented on sickbeard/webapi.py
> +        show_dict["max_size_MB"] = show_obj.max_size_MB
This should be max size in bytes. The only places MB should be used is when a human needs to see the value. Everything else should be translates back and forth to bytes.

2017-04-24 18:16 UTC, OmgImAlexis commented on sickbeard/webserve.py
> +                 defaultEpStatus=None, quality_preset=None, max_size_MB=None):
Change to use bytes.

2017-04-24 18:16 UTC, OmgImAlexis commented on sickbeard/webserve.py
> +                show_obj.max_size_MB = max_size_MB
Change to use bytes.

2017-04-24 18:16 UTC, OmgImAlexis commented on sickbeard/tv.py
> +                        "max_size_MB": self.max_size_MB }
Change to use bytes.

2017-04-24 18:16 UTC, OmgImAlexis commented on sickbeard/tv.py
> +            self.max_size_MB = sql_results[0][b"max_size_MB"]
Change to use bytes.

2017-04-24 18:17 UTC, OmgImAlexis commented on sickbeard/tv.py
> +    max_size_MB = property(lambda self: self._max_size_MB, dirty_setter("_max_size_MB"))
Change to use bytes.

2017-04-24 18:17 UTC, OmgImAlexis commented on sickbeard/tv.py
> +        self._max_size_MB = -1
Change to use bytes.

2017-04-24 18:18 UTC, OmgImAlexis commented
The update for the translations shouldn't be done in this PR. @sharkykh

2017-04-24 19:50 UTC, ArthurGarnier commented
Update done, just not sure if I have to do some conversion in webapi ?

2017-04-25 01:48 UTC, OmgImAlexis commented on sickbeard/webserve.py
> +                show_obj.max_size = str(int(max_size_MB)*1000*1000 if max_size_MB != -1 else -1)
This is still using `max_size_MB`.

2017-04-25 01:48 UTC, OmgImAlexis commented
The API should be fine with returning it in bytes since a developer uses the api and can convert it back to MB if they would like it that way.

2017-04-25 01:55 UTC, OmgImAlexis commented
After reading through the feature request I'm not 100% sold on this being the right way to add it as this adds in a global size limit vs limits per quality setting meaning it doesn't really do what the feature request wanted.

Ideally you'd have user changeable size limits min/max for each quality so for example a `1080p WEB-DL` would be allowed to be from `1GB` - `5GB` where as a `SDTV` copy would only be allowed to go from `100MB` - `500MB`.

2017-04-25 11:37 UTC, ArthurGarnier commented on sickbeard/webserve.py
> +                show_obj.max_size = str(int(max_size_MB)*1000*1000 if max_size_MB != -1 else -1)
Yes it's the value from the field of the UI, as you mentionned the final user have to enter a value in MB (or any other unit, but for the moment I just support MB)

2017-04-25 11:40 UTC, ArthurGarnier commented
I agree that, it's not exactly what the Feature Request ask, but this request is open for more than a year, so it's a good start I think. 
I can do this for each quality but it will take more time

2017-04-25 11:43 UTC, OmgImAlexis commented
@miigotu thoughts?

2017-04-26 12:43 UTC, miigotu commented
More time is fine, there is no rush on any db updates quite yet =P
Nearly there for the next db update, just not yet.

2017-05-05 22:43 UTC, ArthurGarnier commented
Just a question, it should be a set of parameter by show or a global one ?

2017-05-08 15:09 UTC, beschoenen commented
I'd like to have a minimum size, too. Eliminating the issue of download really bad 720p videos.
Is that something you could add in here? Or maybe another PR.

2017-05-08 15:13 UTC, sharkykh commented
@ArthurGarnier in my mind per show with default setting (think like the show settings)

2017-05-09 01:22 UTC, miigotu commented
Yeah, both global and per-show, with the show's setting overriding the global setting

2017-05-09 08:03 UTC, ArthurGarnier commented
@beschoenen Yes it could be added too, probably in the same PR, it's almost the same work

2017-05-09 08:11 UTC, OmgImAlexis commented
This really needs not only global and per show settings but per quality settings otherwise this only prevents the high res qualities downloading large files but doesn't really prevent things like a 5GB SD file vs a 5GB HDTV file.

2017-05-09 12:37 UTC, ArthurGarnier commented
Yes, 
So we will have : 2 tables in show settings and global settings : 
* Quality 1 : Min size | Max Size
* Quality 2 : Min size | Max Size
* ...

2017-05-09 14:00 UTC, beschoenen commented
The best solution, in my opinion, is to move qualities to a separate table.
This will also give us the ability to make custom qualities, with custom names, etc..

2017-07-04 04:30 UTC, julienld commented
@ArthurGarnier 
It also could have been a size relative to the length of the show : X MB per minute of the show. For example a 40 MB/min limit for a 20 minutes show would have an 600MB limit and a 40 minute show would have an 1.2GB limit... This would almost never require a per show setting to be set.

The number of minute per episode is in show.imdb_info['runtimes']. It's also available in the 'runtime' property of TheTVDB (but not saved right now... I think).

This is not perfect because some episodes are double feature and the runtime does not take this into account... but it still an issue with the current way to do it.

Also, i'm not sure this should have been implemented as 2 hard limit (low and high). I could have one setting : "Ideal size". From the ideal size, you could calculate a penalty for a too big of too small file.  The less ideal the file size is, bigger the penalty. This penalty could be applied when selecting the source for the episode.

As side effect, this would ensure a double-feature would still be downloaded because it's would not be an hard limit.

2017-07-04 06:14 UTC, OmgImAlexis commented
@julienld there would be a lot of false positives since things can change the torrent size like the codec used, if it has ads, trailers, etc., if it's compressed in a rar file, if there's a sample, etc..

2017-11-05 00:29 UTC, mgaulton commented
Curious if there's been any additional progress on this? I'd really like this particular feature.

2017-11-06 23:15 UTC, ArthurGarnier commented
Personally, didn't get any time for this. But I think I'll take few hours in next few weeks

2018-03-23 11:53 UTC, cannondale0815 commented
I want to bump this up. I would love a file size limit for episodes, so that I can just tell SickRage to download files in "HD" and trust that whatever files it chooses to download don't exceed the individual file size limit I set (i.e. 2GB). Can this development be dusted off and integrated into the master?

2018-03-27 02:39 UTC, sjdaws commented
I have developed a branch which checks sizes for usenet however it currently uses arrays of static sizes based on quality as I don't know how to implement this into the UI.

If someone wants to run with it: https://github.com/SickRage/SickRage/compare/master...sjdaws:master

2018-04-04 10:44 UTC, rwyarbrough commented
This functionality would be greatly appreciated in the community.  More and more files are being created with less compression. Some of them are enormous. Not having an option to set a min or max file size is resulting in them having to be discarded and smaller sized files manually added much more frequently of late which takes away the benefit of the automatic operation of SickBeard.

2018-04-16 14:24 UTC, Tiwas commented
*bump*

I have some other requests and takes on requests here in this thread: #4595

2018-08-12 15:41 UTC, Nosirus requested changes
I need too, it downloads me otherwise seasons of 80Gb see more

2018-11-05 02:30 UTC, miigotu commented
I was going to use this as a base for the DB upgrade, but the patch/diff is gone since the repo is gone...

2018-11-05 09:41 UTC, closed without merging

2018-11-07 17:38 UTC, mgaulton commented
@miigotu Is this a dead feature or are you just reevaluating?

2018-11-07 17:57 UTC, miigotu commented
@mgaulton I will be doing it myself, since this PR isnt able to be applied anymore

2018-11-09 01:11 UTC, cannondale0815 commented
@miigotu Thank you -- we all appreciate it and are looking forward to this feature! :)