Fix split-RAR files detection
SickChill/sickchill pull request #3686
Opened 2017-04-28 13:12 UTC by sharkykh

Should fix #3674 

See:
* http://i.imgur.com/yz0wxSR.png
* https://regex101.com/r/eMPi3p/7

2017-04-28 19:55 UTC, rubdos commented
> https://regex101.com/r/eMPi3p/9 (only_first = False)
> https://regex101.com/r/yM9BOp/3 (only_first = True default)

Why is `only_first` per default `False`? Most scene has the older style.

2017-04-28 20:02 UTC, sharkykh commented
@rubdos 
On the contrary, the default is `True`.

The reason for that is,
`is_rar_file` is used by the postprocessor to determine which files need to be extracted.
Without `only_first` (or when it's set to False), it would try to unpack/unrar every possible rar file:
`.rar, .part1.rar, .part9.rar, .r00, .r09`, etc.

I use `only_first` only for when unpack method is set to "Treat as video" and I need to process all of the rar files and parts to move them all together, like you asked.

2017-04-28 20:21 UTC, rubdos commented
> On the contrary, the default is True.

Whooooops, typo :)

> The reason for that is,
> is_rar_file is used by the postprocessor to determine which files need to be extracted.
> Without only_first (or when it's set to False), it would try to unpack/unrar every possible rar file:
> .rar, .part1.rar, .part9.rar, .r00, .r09, etc.
> 
> I use only_first only for when unpack method is set to "Treat as video" and I need to process all of the rar files and parts to move them all together, like you asked.

Ok, I get it. It seemed a bit weird to me, that's why I asked. Thanks for the fix !

2017-04-29 07:16 UTC, miigotu requested changes

2017-04-29 07:16 UTC, miigotu commented on sickbeard/helpers.py
> +        is_rar = is_rar_file(filename, only_first=False)
doing this unconditionally wont work, its going to process ear rar piece as a separate video and process them all, overwriting the previous one as it goes (unless renaming is off)

2017-04-29 07:22 UTC, sharkykh commented
@miigotu 
In that case, associated files is the way to go. That complicates things a bit.

2017-04-29 07:23 UTC, sharkykh commented on sickbeard/helpers.py
> +        is_rar = is_rar_file(filename, only_first=False)
@miigotu 
In that case, associated files is the way to go. That complicates things a bit.

2017-04-29 07:25 UTC, miigotu commented
I would suggest adding a check just after the treat_as_video and move/link/copy/etc them separately, idk

2017-05-05 11:49 UTC, closed without merging