Fixed yggtorrents login issue
SickChill/sickchill pull request #4223
Opened 2017-12-28 08:50 UTC by phtagn

Fixes #

Proposed changes in this pull request:
- Fixes yggtorrent's login check logic
- Sanitize search string to remove characters that are not allowed on the site.
-

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

2017-12-30 22:55 UTC, PHD59fr commented
I do not understand why you are trying to change the login verification system, we dont use 'find_all' against an 'in'.

When you call the page "https://yggtorrent.com/" , it will return the logged page with "logout" inside

```
root@NUNUX:~# python -m timeit 'temp = "https://yggtorrent.com/user/logout";temp.find("logout")'
10000000 loops, best of 3: 0.0929 usec per loop
root@NUNUX:~# python -m timeit 'temp = "https://yggtorrent.com/user/logout";"logout" in temp'
10000000 loops, best of 3: 0.0325 usec per loop
```
for the format of the search string, i think you can use urlencode

2017-12-30 23:05 UTC, PHD59fr requested changes

2017-12-30 23:05 UTC, PHD59fr commented on sickbeard/providers/yggtorrent.py
> +        self.url = 'https://yggtorrent.com/'
OK for me

2017-12-30 23:05 UTC, PHD59fr commented on sickbeard/providers/yggtorrent.py
> +            'login_check': urljoin(self.url, 'user/account'),
Useless: login_check and logout

2017-12-30 23:05 UTC, PHD59fr commented on sickbeard/providers/yggtorrent.py
> +            response = self.get_url(self.urls['login_check'], returns='text')
Test just on index, it's on for check:
`<li><a href="https://yggtorrent.com/user/logout"><i style="font-size:17px; vertical-align: middle;" class="fa fa-sign-out" aria-hidden="true"></i></a></li>`

2017-12-30 23:05 UTC, PHD59fr commented on sickbeard/providers/yggtorrent.py
> +        html = BS4Parser(response, 'html5lib')
for perf use 'in', reponse is a string

2017-12-30 23:05 UTC, PHD59fr commented on sickbeard/providers/yggtorrent.py
> +                # search string needs to be normalized, single quotes are apparently not allowed on the site
OK for me

2017-12-31 00:33 UTC, phtagn commented
Hi,

I am not saying this is better. It stopped working and I thought it was because it didn’t find ‘logout’ on the page. I changed this and a few other things at the same time and I didn’t check what solved the issue, sorry. 
If you want I can revert to using ‘in’ that’s fine, or you can disregard the pull request entirely. Honestly, I now think it was just an URL issue, so changing from ww1.yggtorrent.com to yggtorrent.com may have solved it alone. 
What is necessary on the other hand is to sanitize the search string and remove apostrophe. Otherwise you can’t find any of the marvel shows as they’re named, for example, « Marvel’s Iron Fist ». Replacing ç with c also helps, when you’re searching for « fais pas ci, fais pas ça », but that does not happen very frequently. 

> Le 30 déc. 2017 à 23:55, PHD <notifications@github.com> a écrit :
> 
> I do not understand why you are trying to change the login verification system, we dont use 'find_all' against an 'in'.
> 
> When you call the page "https://yggtorrent.com/" , it will return the logged page with "logout" inside
> 
> root@NUNUX:~# python -m timeit 'temp = "https://yggtorrent.com/user/logout";temp.find("logout")'
> 10000000 loops, best of 3: 0.0929 usec per loop
> root@NUNUX:~# python -m timeit 'temp = "https://yggtorrent.com/user/logout";"logout" in temp'
> 10000000 loops, best of 3: 0.0325 usec per loop
> for the format of the search string, i think you can use urlencode
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-12-31 00:45 UTC, phtagn commented
I’ve amended the file per your comments. Do you want to keep the sanitization part or should I delete it also ?

Kind regards

> Le 31 déc. 2017 à 00:05, PHD <notifications@github.com> a écrit :
> 
> @PHD59fr requested changes on this pull request.
> 
> In sickbeard/providers/yggtorrent.py <https://github.com/SickRage/SickRage/pull/4223#discussion_r159130875>:
> 
> > @@ -48,10 +49,12 @@ def __init__(self):
>          self.minleech = None
>  
>          # URLs
> -        self.url = 'https://ww1.yggtorrent.com/'
> +        self.url = 'https://yggtorrent.com/'
> OK for me
> 
> In sickbeard/providers/yggtorrent.py <https://github.com/SickRage/SickRage/pull/4223#discussion_r159130883>:
> 
> >          self.urls = {
>              'login': urljoin(self.url, 'user/login'),
>              'search': urljoin(self.url, 'engine/search'),
> +            'login_check': urljoin(self.url, 'user/account'),
> Useless: login_check and logout
> 
> In sickbeard/providers/yggtorrent.py <https://github.com/SickRage/SickRage/pull/4223#discussion_r159130908>:
> 
> > @@ -71,12 +74,13 @@ def login(self):
>  
>          response = self.get_url(self.urls['login'], post_data=login_params, returns='text')
>          if not response: # When you call /login if it's OK, it's return 200 with no body, i retry in main if it's logged !
> -            response = self.get_url(self.url, returns='text')
> +            response = self.get_url(self.urls['login_check'], returns='text')
> Test just on index, it's on for check:
> <li><a href="https://yggtorrent.com/user/logout"><i style="font-size:17px; vertical-align: middle;" class="fa fa-sign-out" aria-hidden="true"></i></a></li>
> 
> In sickbeard/providers/yggtorrent.py <https://github.com/SickRage/SickRage/pull/4223#discussion_r159130916>:
> 
> >              if not response: # The provider is dead !!!
>                  logger.log('Unable to connect to provider', logger.WARNING)
>                  return False
>  
> -        if 'logout' not in response:
> +        html = BS4Parser(response, 'html5lib')
> for perf use 'in', reponse is a string
> 
> In sickbeard/providers/yggtorrent.py <https://github.com/SickRage/SickRage/pull/4223#discussion_r159130919>:
> 
> > @@ -96,6 +100,18 @@ def search(self, search_strings, age=0, ep_obj=None):  # pylint: disable=too-man
>                  if mode != 'RSS':
>                      logger.log('Search string: {0}'.format
>                                 (search_string.decode('utf-8')), logger.DEBUG)
> +                # search string needs to be normalized, single quotes are apparently not allowed on the site
> OK for me
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/SickRage/SickRage/pull/4223#pullrequestreview-86037943>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AQgfee-v6GCl666743kM4Il1n2yPSzHOks5tFsHAgaJpZM4ROIRM>.
>

2018-01-01 23:52 UTC, PHD59fr approved these changes

2018-01-08 03:38 UTC, miigotu commented on sickbeard/providers/yggtorrent.py
> +from lib.js2py.translators.pyjsparser import false
?

2018-01-08 06:54 UTC, phtagn commented on sickbeard/providers/yggtorrent.py
> +from lib.js2py.translators.pyjsparser import false
Hi, sorry, did not realize that was in there. No reason for it to be, it was automatically generated by the IDE. I just removed it.

2018-01-08 23:09 UTC, PHD59fr commented on sickbeard/providers/yggtorrent.py
> +from lib.js2py.translators.pyjsparser import false
It's OK now, can u merge the branch please ?

2018-01-10 07:20 UTC, miigotu commented
Copied your commits to a new branch and fixed the build in #4239

2018-01-10 07:20 UTC, closed without merging