Change url generation to dowload torrents for Torrent9.
SickChill/sickchill pull request #4719
Opened 2018-05-20 23:07 UTC by czotti

Fixes #4716

Proposed changes in this pull request:
- change the torrent9 provider to support their new urls.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickRage/SickRage/blob/master/.github/CONTRIBUTING.md)

2018-05-21 08:08 UTC, jlejeune commented on sickbeard/providers/torrent9.py
> +                    if torrent_table is not None:
if torrent_table:  # is enough

2018-05-22 11:11 UTC, jlejeune approved these changes

2018-05-22 12:07 UTC, lagaisse approved these changes

2018-05-24 16:02 UTC, rdehouss commented
This MR works for me, thx!

2018-05-25 08:35 UTC, Jamyz commented
Great, Thanks...

2018-05-26 01:18 UTC, czotti commented
The failing part of appveyor can be easily removed by changing the line 60 from:
`"pip install --disable-pip-version-check --user --upgrade pip"`
to:
`"python -m pip install --disable-pip-version-check --user --upgrade pip"`

Can I do this here or in a new PR ?

2018-06-08 18:18 UTC, fly320 approved these changes

2018-06-11 12:16 UTC, Jamyz approved these changes
Works Good... Thanks to push soon.

2018-06-11 12:18 UTC, Jamyz requested changes
Works Good....Push it Soon I Hope.....

2018-06-16 05:51 UTC, merged