Update README w/ more links, clearer language
SickChill/sickchill pull request #5078
Opened 2018-10-15 20:31 UTC by jamiew

Plus a note about when the `sickrage/sickrage` repository takeover happened

I also made a number of edits to the wiki for clarity: [recent edits list](https://github.com/SickChill/SickChill/wiki/Home/_history)

* edit1 (sidebar) https://github.com/SickChill/SickChill/wiki/Home/983bccbc96887e20ca3c0cf4ad4c206efc6c804d
* edit2 (main page text) https://github.com/SickChill/SickChill/wiki/Home/435e2ef450577cc24d8e142e5a4d851ff42a8f77

2018-10-16 02:05 UTC, miigotu requested changes

2018-10-16 02:05 UTC, miigotu commented on readme.md
> +![image](https://rarbg.com/favicon.ico)[RARBG](https://rarbg.to) <br/>
dont usev `<br/>` - Just put 2 spaces at the end of the line

2018-10-16 02:05 UTC, miigotu commented on readme.md
> +Automatic Video Library Manager for TV Shows. Watches for new episodes of your favorite shows, and sends them to your downloader whenever they're available.
Leave this line how it was, for legal reasons.

2018-10-16 02:05 UTC, miigotu commented on readme.md
> +To run SickChill from source you will need Python 2.7.10
The `from source` part can be taken out, we always need python 2.7.10+ whether its a zip install or a git install.

2018-10-23 18:04 UTC, jamiew commented
Was this closed as n/a, or just closed because needs updates? I can revisit your notes later this week

2018-10-23 18:07 UTC, jamiew commented on readme.md
> +![image](https://rarbg.com/favicon.ico)[RARBG](https://rarbg.to) <br/>
All sane text editors strip that out (and I noticed it was already missing) so I end up needing to force it. This and image-link syntax are horrible parts of markdown IMHO

2018-10-23 21:54 UTC, miigotu commented
Just because you didnt respond =P

2018-10-27 06:04 UTC, miigotu commented
@jamiew so whats going on =P

2018-10-27 17:00 UTC, jamiew commented
@miigotu implemented your suggestions except for EOL double-spaces since text editors have been stripping that, should be gtg now

I have more changes I'd like to make here (and in the wiki) but prefer to keep PRs small and moving along

Thanks for your patience, mediacenter contributions are a weekend activity for me :)

2018-10-28 02:32 UTC, miigotu approved these changes

2018-10-28 02:39 UTC, merged

2018-10-28 02:40 UTC, miigotu commented
Make sure future PR are against the develop branch please =P

2018-10-28 11:54 UTC, jamiew commented
Ah will do

Any thoughts about switching from master/develop to master/stable or master/release? 

> On Oct 27, 2018, at 10:40 PM, miigotu <notifications@github.com> wrote:
> 
> Make sure future PR are against the develop branch please =P
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-10-28 12:01 UTC, miigotu commented
Master is release/stable.