Deluged: add download and completed dirs to config
SickChill/sickchill pull request #5495
Opened 2019-05-21 06:34 UTC by doucheymcdoucherson

Fixes #5476

Proposed changes in this pull request:
- Adds "download directory" and "completed directory" options to "Deluge (via Daemon)". This allows the user to configure the initial download location rather than using the default one set by Deluge. The previous behavior prior to this commit was to only set the "completed directory". Does not effect "Deluge (via WebUI)".

2019-05-22 13:02 UTC, miigotu requested changes

2019-05-22 13:02 UTC, miigotu commented on sickbeard/clients/deluged_client.py
>      def _set_torrent_path(self, result):
This is called right after adding the torrent, not after the torrent is complete. Is this correct to change the path right after adding? I would think it would start downloading at TORRENT_DELUGE_DOWNLOAD_DIR and you would immediately move it to TORRENT_DELUGE_COMPLETE_DIR without waiting for it to finish,

2019-05-22 13:02 UTC, miigotu commented on gui/slick/views/config_search.mako
> +                                                    <label id="path_synology"><b>${_('note')}:</b> ${_('the destination has to be a shared folder for Synology DS</span>')}</label>
please change the label id to torrent_deluge_complete_dir_deluge (I think)

2019-05-22 13:02 UTC, miigotu commented on gui/slick/views/config_search.mako
> +                                                    <label id="path_synology"><b>${_('note')}:</b> ${_('the destination has to be a shared folder for Synology DS</span>')}</label>
Please change the id to torrent_download_dir_deluge (I think)

2019-05-22 13:02 UTC, miigotu commented on gui/slick/views/config_search.mako
> +                                    <div class="field-pair row" id="torrent_deluge_download_dir_option">
torrent_deluge_download_dir_option and torrent_deluge_complete_dir_option can be in the same div, and hidden/shown as one unit so there is less js

2019-05-22 17:41 UTC, doucheymcdoucherson commented on sickbeard/clients/deluged_client.py
>      def _set_torrent_path(self, result):
Both options can be set right away when the call is made to Deluge. The TORRENT_DELUGE_COMPLETE_DIR is only used when the torrent finishes downloading. 

In the below screenshot from Deluge:
 "Download Location" = TORRENT_DELUGE_DOWNLOAD_DIR
"Move Completed Location" = TORRENT_DELUGE_COMPLETE_DIR

![Capture](https://user-images.githubusercontent.com/460545/58195791-a5725300-7c7d-11e9-9e61-3e1384106618.PNG)

2019-05-22 18:46 UTC, doucheymcdoucherson commented on gui/slick/views/config_search.mako
> +                                                    <label id="path_synology"><b>${_('note')}:</b> ${_('the destination has to be a shared folder for Synology DS</span>')}</label>
@miigotu Should it be "torrent_complete_dir_deluge" instead to match "torrent_download_dir_deluge"?

2019-05-22 19:05 UTC, doucheymcdoucherson commented on gui/slick/views/config_search.mako
> +                                                    <label id="path_synology"><b>${_('note')}:</b> ${_('the destination has to be a shared folder for Synology DS</span>')}</label>
changed in 79f9e0f7b170ee040badc6189a556838d26750af

2019-05-22 19:06 UTC, doucheymcdoucherson commented on gui/slick/views/config_search.mako
> +                                    <div class="field-pair row" id="torrent_deluge_download_dir_option">
changed in 79f9e0f7b170ee040badc6189a556838d26750af

2019-05-22 19:07 UTC, doucheymcdoucherson commented on gui/slick/views/config_search.mako
> +                                                    <label id="path_synology"><b>${_('note')}:</b> ${_('the destination has to be a shared folder for Synology DS</span>')}</label>
changed in 79f9e0f7b170ee040badc6189a556838d26750af

2019-05-24 11:42 UTC, miigotu commented on gui/slick/views/config_search.mako
> +                                            <div class="row">
Just delete this whole div. Its a note under the path for the synology path you copied this from that says the folder has to be a shared folder on synology, which isnt true for deluged

2019-05-24 11:58 UTC, miigotu requested changes
I deleted those divs, all good to go!

2019-05-24 11:58 UTC, miigotu commented on gui/slick/views/config_search.mako
> +                                            <div class="row">
Just delete this whole row div. Its a note under the path for the synology path you copied this from that says the folder has to be a shared folder on synology, which isnt true for deluged

2019-05-24 11:58 UTC, miigotu commented on gui/slick/views/config_search.mako
> +                                            <div class="row">
Just delete this whole row div. Its a note under the path for the synology path you copied this from that says the folder has to be a shared folder on synology, which isnt true for deluged

2019-05-24 11:58 UTC, miigotu commented on sickbeard/clients/deluged_client.py
>      def _set_torrent_path(self, result):
I understand how you expect it to work, its just not easy to see in the code that it works that way because of the introspection and a lack of deluged rpc docs.

Im just worried that set_torrent_path will just change the download location rather than setting the completed location like intended, or another criss-criss because I cannot verify with docs.

Either way, worst case scenario is it will just need fixed if an issue pops up, Ill just have to trust that you made the calls and checked with differing values to see that it works because Im not interested in installing deluge to check for purpose of review :)

2019-05-24 12:07 UTC, merged

2019-05-24 12:11 UTC, miigotu commented
Thanks