Implementation suggestion for "Prefer words" (#5629)
SickChill/sickchill pull request #5699
Opened 2019-11-18 18:55 UTC by markprins

PR Is based my own wishes and needs for a "Prefer words" option as is discussed in #5629 

As much as possible I tried to follow current guidelines and general best-practices. I also tried to contact dev-time on IRC to get some pointers/suggestions on how to create more specific unit-tests to help.

Unfortunately I was not able to get any specific help, so I hope that by using this pull-request I can get some help for merging.

To layout the implemented changes:

- Added hasPreferedWords to show_name_helper
- hasPreferedWords goes through the fetched results and finds out if any of the prefered words are in the list
- If no prefered words exists, it does nothing
- If prefered words exists, it will return a sorted list with the most prefered item at the top
- Also has unit tests available which should capture any issues
- Implements a prefered words option in the settings
- Implements a DB migration (although Im not really sure I did it correct)

(be gentle and/or poke me on IRC, though time-zones may make this tricky)

2019-11-19 14:37 UTC, WebSpider commented
Please point this merge request to the develop branch

2019-11-19 14:40 UTC, markprins commented on sickbeard/search.py
> +
Notised I left debugging/logging statements. Will update later

2019-12-12 08:59 UTC, miigotu commented
Is this ready for a merge?

2019-12-15 07:21 UTC, markprins commented
I've updated the PR with the latest changes from develop.

Have been running my version locally without problems (works like a charm). It should be ready for merge, but as stated in the pull-request, I'm not entirely sure that I did all the db migrations correctly and if it is up-to-spec.

2019-12-18 02:05 UTC, miigotu requested changes
All looks good except these few things with the DB version. We want to use minor db versions for smaller changes like this for now

2019-12-18 02:05 UTC, miigotu commented on sickbeard/databases/mainDB.py
> +        return self.get_db_version() >= 45
```python
        return self.has_column("tv_shows", "rls_prefer_words")

```

2019-12-18 02:05 UTC, miigotu commented on sickbeard/databases/mainDB.py
> +MAX_DB_VERSION = 45
Leave this at 44

2019-12-18 02:05 UTC, miigotu commented on sickbeard/databases/mainDB.py
> +        self.increment_db_version()
self.inc_minor_version()

2019-12-18 02:05 UTC, miigotu commented on sickbeard/databases/mainDB.py
> +class ResetDBVersion(AddPreferWords):
Remove this reset class. db should be 44.1 after this pr

2019-12-18 18:32 UTC, markprins commented
> All looks good except these few things with the DB version. We want to use minor db versions for smaller changes like this for now

I have incorporated the suggested changes as you described.

As I was running for a few weeks with my branch, I was wondering how I would go about "fixing" my database so it _thinks_ it is the same as would be when it migrates to a new minor version (so I don't need to revert back to my previous db from a month or so back and re-scan everything). Is there an easy fix for that? (I'd think something like set the version manually or something like that).

2019-12-19 20:12 UTC, miigotu commented
@markprins Use sqlite3 or another sqlite db editor and change db_version.db_version to 44 and db_version.db_minor_version to 1

If using sqlite3:
```bash
sqlite3 /path/to/sickbeard.db
```
```sql
UPDATE db_version SET db_verion=44, db_minor_version=1;
```

2019-12-19 20:16 UTC, miigotu approved these changes

2019-12-19 22:05 UTC, miigotu commented
@markprins sorry I used your branch for a sandbox to fix the windows build tests. Hopefully it is working now.

2019-12-19 22:53 UTC, merged