Improve anime series detection
SickChill/sickchill pull request #6673
Opened 2020-08-25 20:30 UTC by Nyaran

Fixes #6646 

Proposed changes in this pull request:
- After guessing the show, if is marked as anime, try to use first the regular expressions marked as "anime"

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

2020-08-25 20:45 UTC, miigotu requested changes

2020-08-25 20:45 UTC, miigotu commented on sickchill/oldbeard/name_parser/parser.py
> +        matches = list(filter(lambda x: x.series_name, matches))
Don't use list(filter()) or lambdas if it can be helped.

List comprehension works best here:
`[x for x in matches if x.series_name]`

2020-08-25 20:45 UTC, miigotu commented on sickchill/oldbeard/name_parser/parser.py
>                      show = None
Let's not use filter/lambda here either (I know other parts of the file do, they need updated)

```python
from operator import attrgetter
sorted([x for x in matches if x.is_anime], reverse=True, key=attrgetter('which_regex'))
```

2020-08-25 20:46 UTC, miigotu commented
Also, I'm not quite sure what's going on because only anime regexes are compiled for anime shows? I'll have to review this on my PC later

2020-08-25 20:52 UTC, miigotu commented on sickchill/oldbeard/name_parser/parser.py
>                      show = None
https://stackoverflow.com/questions/2705104/lambda-vs-operator-attrgetterxxx-as-a-sort-key-function#:~:text=attributename%20as%20a%20sort%20key,faster%20option%20of%20the%20two.&text=So%20applying%20attrgetter(%27bar,as%20produced%20by%20attrgetter()%20.

2020-08-25 20:57 UTC, miigotu commented on sickchill/oldbeard/name_parser/parser.py
> +                        show_anime = helpers.get_show(bestResult.series_name, self.tryIndexers)
We should not try indexers here, just pass False

2020-08-25 20:57 UTC, miigotu commented on sickchill/oldbeard/name_parser/parser.py
> +                        if show_anime.indexerid == show.indexerid:
```python
if show_anime and show_anime.indexerid == show.indexerid:
```

2020-08-25 21:08 UTC, Nyaran commented
> Also, I'm not quite sure what's going on because only anime regexes are compiled for anime shows? I'll have to review this on my PC later

The "anime" check could be a bit confusing, as is not valid for all animes, only for the anime with absolute numbering.

e.g. One Piece uses absolute numbering, but other animes, like "To Aru Kagaku no Railgun", uses season numbering (like any other show).
 
In the past, there was two different options (I'm sure as I added the anime support to SickBeard time ago...), but time later the options was merged

Anyway, this is just a "quick" proposal, and could be improved or re-thinked

2020-08-25 21:16 UTC, miigotu commented
I think I understand why this is needed, it is when the show is not known (it's during post processing) so both normal and anime regexes are compiled.

I'd like to help make some improvements on this PR on the surrounding code.

Can you enable maintainer permissions on the PR? I'm sure there is a user-wide setting to always do this, but you can do it per-pr also:

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

2020-08-25 21:20 UTC, Nyaran commented
> I think I understand why this is needed, it is when the show is not known (it's during post processing) so both normal and anime regexes are compiled.
> 
> I'd like to help make some improvements on this PR on the surrounding code.
> 
> Can you enable maintainer permissions on the PR? I'm sure there is a user-wide setting to always do this, but you can do it per-pr also:
> 
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

All my PRs (except that one I created as a draft days ago...) have it active

2020-08-25 21:27 UTC, Nyaran commented
> I think I understand why this is needed, it is when the show is not known (it's during post processing) so both normal and anime regexes are compiled.

Exactly, so, a first attempt is necessary to guess the show. Maybe a better option could be to use [guessit](https://github.com/guessit-io/guessit).

BTW, what do you think to re-separate the anime and absolute numbering options again? I think is better with two options as one thing is mark the show as an anime (to use anidb information and/or to use the separate shows and anime option) and another thing is to use absolute numbering on some anime (but not on all, as I explained)

If you are agree, I will try to work it on another branch

2020-08-25 21:29 UTC, Nyaran commented
I see some test failing, It's late where I am (Spain, GMT+1), but I will try to fix it tomorrow.

2020-08-25 22:20 UTC, miigotu commented on sickchill/oldbeard/name_parser/parser.py
> +                        show_anime = helpers.get_show(best_result_anime.series_name)
You intended to get_show with `best_result_anmie.series_name` here right? It was `best_result.series_name` so `show.indexerid` was always the same as `show_anime.indexerid`.

2020-08-25 22:22 UTC, miigotu commented
@Nyaran you can test locally with tox.

I fixed it, https://github.com/SickChill/SickChill/pull/6673/files#diff-3ea1e6ad9cf013f2ebca6dcc5ac181e3R191

2020-08-27 00:21 UTC, miigotu commented
@Nyaran does this still work to process those animes correctly? Agree with my adjustments?

2020-08-27 14:52 UTC, Nyaran commented on sickchill/oldbeard/name_parser/parser.py
> +                        show_anime = helpers.get_show(best_result_anime.series_name)
It's just an extra check to be sure the new regular expression is not getting any other string as "series_name"

2020-08-27 15:11 UTC, Nyaran commented
> @Nyaran does this still work to process those animes correctly? Agree with my adjustments?

Is working well for "Yu.Yu.Hakusho.-.034.-.1080p.BluRay.x264.DHD.mkv"

For "One Piece - 921.mkv", is not working, because the "best result" doesn't contains a series name (is stored group name)
![Captura de pantalla de 2020-08-27 17-11-12](https://user-images.githubusercontent.com/1042532/91460645-55bf0600-e888-11ea-9955-8461f524d8d0.png)

2020-08-28 16:36 UTC, Nyaran commented
Ok, now we have test for those names, and the name "Show Name - 102" is failing when it have to guess if the name is for an anime show or not.

@miigotu I think we can merge "as is" (removing the failing test), and continue working on another branch/PR

2020-08-28 16:55 UTC, miigotu commented
I think that test should return anime_bare and not "stupid", just need to change the expected result for that test string.

Definitely want everything passing before merge.

2020-08-28 16:59 UTC, miigotu commented
Yes, add `@expectedFailure` or something to that test, because honestly I think anime_bare without a release group is extremely rare (and for some reason I think we add `-SICKCHILL` to the string and try again anyway)

2020-08-28 17:38 UTC, miigotu commented
I'm gonna try to fix that a bit further. Commits coming soon

2020-08-28 19:00 UTC, merged