Notifications clear sub notify settings
SickChill/sickchill pull request #8397
Opened 2023-03-26 13:42 UTC by BKSteve

Fixes some notifications still attempting to send when main selector is deselected.

traceback.format_exc() inserted per #8339
and other partial notification issue items #8318  #8258

2023-03-27 04:29 UTC, miigotu requested changes
I think this approach breaks a few things.

2023-03-27 04:29 UTC, miigotu commented on sickchill/oldbeard/notifications_queue.py
> -                raise error
Imo this should be:
```python
                logger.exception(traceback.format_exc())
                raise error
```

2023-03-27 04:29 UTC, miigotu commented on sickchill/oldbeard/notifications_queue.py
> -            logger.exception(f"Error Sending Discord message: {error}")
```python
            logger.exception(f"Error Sending Discord message: {error}")
            logger.exception(f"Traceback: {traceback.format_exc()}")
```

2023-03-27 04:29 UTC, miigotu commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
Every change in here I think is the wrong way to do this. The settings should always be read, or they will be saved wrong on every shutdown.

Instead, make sure the methods in each notifier check that the notifier is enabled (they already should be, some are probably just missed)

Pseudo code example:

```python
class DiscordNotifier:
    def notify_subtitles(self, x):
        if settings.DISCORD_NOTIFY_SUBTITLES:
            return self.send_discord(x)

    def send_discord(self, x):
        if settings.USE_DISCORD:
            return discord.send(x)
```

2023-03-27 05:40 UTC, BKSteve commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
The discord part wasn't changed, the code change was just clearing the settings of sub items when you deselect the main check box and then do a save. 
As there is currently no check for the main item if a notification and the sub item is checked for notification it sends. So if you've set it before and then disable there is nothing that clears the sub items and thus some errors being thrown. 
The other way is to check the main item before the sub item in the queue. I thought this was easier 🪜

2023-03-27 05:40 UTC, BKSteve commented on sickchill/oldbeard/notifications_queue.py
> -                raise error
noted

2023-03-27 08:55 UTC, BKSteve commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
the `config_notifications.mako` loads all of them so when the save button is clicked they get saved in config.ini just as before.

2023-03-28 14:09 UTC, BKSteve commented
#8339 code fix added.

2023-03-29 15:58 UTC, miigotu commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
The settings shouldn't be cleared though, they just shouldn't be used if it's disabled when the code calls a notifier. My pseudoecode was showing how it should work, it wasn't specific to discord.

2023-03-29 16:20 UTC, BKSteve commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
Point taken and understood. 
This was the lazy way, if main selector unchecked write uncheck to all child items when Martin page save is clicked whilst leaving data. Should it be reenabled then a few check boxes and save.

2023-03-29 19:47 UTC, miigotu commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
im going to check trhe code and see where the missed if was in the notifiers, and push it to this PR so the ui changes can go back.

2023-03-30 05:04 UTC, BKSteve commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
I understand but if you unselect the main item then you don't want any of the sub items. You don't then need to chase down all the other code that only refers to the sub items.

2023-03-30 18:53 UTC, miigotu commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
You need it to retain the settings though. You might just be disabling a notifier temporarily.

It's not chasing it down, the notifiers have a base class, and all of the notifier methods check if it's enabled before it tries to send anything.

2023-03-30 18:56 UTC, miigotu commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
If I disabled something for a test or temporary because a service was down or something, and then when re-enabling I had to go find all my passwords and API keys and urls or whatever settings for that notifier just to re-enablr it is be pissed.

2023-03-31 01:47 UTC, BKSteve commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
That's why only clear check boxes all other data stays.

2023-04-03 10:09 UTC, BKSteve commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
Does the `fix kodi only` pull work better for you? 

Can revert the `notifications.py` and then go through all the other `notifiers>*.py`

2023-04-05 06:23 UTC, BKSteve commented on sickchill/views/config/notifications.py
> -        settings.KODI_ALWAYS_ON = config.checkbox_to_value(kodi_always_on)
Fully revised

2023-05-12 04:16 UTC, BKSteve commented
Bump

2023-05-28 10:32 UTC, BKSteve commented
> I think this approach breaks a few things.

Totally removed those changes to notification.py and fixed up the others

2023-05-28 13:26 UTC, miigotu commented
Yeah I'll go over this tonight and see about merging it. It looks better for sure, I just don't have time to do an actual review right now.

2023-05-28 17:56 UTC, miigotu commented on sickchill/gui/slick/views/config_notifications.mako
> +                                        <label><b>${_('note')}:</b>&nbsp;${_('requires SickChill to be running on your Synology NAS (DSM 6 only).')}</label>
This is also older DSM versions, not just DSM 6.

2023-05-28 18:23 UTC, merged

2023-05-29 07:27 UTC, BKSteve commented on sickchill/gui/slick/views/config_notifications.mako
> +                                        <label><b>${_('note')}:</b>&nbsp;${_('requires SickChill to be running on your Synology NAS (DSM 6 only).')}</label>
DSM 5 doesn't have putting 3