toDelete combos
SickChill/sickchill pull request #8568
Opened 2023-09-27 16:36 UTC by BKSteve

tweak core.js to work with all massUpdates and massEdits, many combos tested

2023-09-27 23:51 UTC, miigotu requested changes, later dismissed
This completely breaks what is supposed to be happening, I'll go back and test it again but I know it was working, it just works different than it used to because I changed the entire form structure from 2 separate forms to 1 form.

2023-09-27 23:51 UTC, miigotu commented on sickchill/gui/slick/js/core.js
> +                            form.submit();
The form is not supposed to get submitted here. Delete and all of the other items are done in the same form. There is only one form submit.

2023-09-27 23:51 UTC, miigotu commented on sickchill/gui/slick/js/core.js
> +                    submit = false;
This doesn't make any sense, if previous checks already set it to true it needs to stay true. It's not two separate forms now, it's one combined form. If we don't confirm the delete, it's still supposed to continue on and submit the form later just without the toDelete inputs added. If confirmed we add the toDelete inputs and set it to be submitted. The code was correct before, it's just not submitting how you think it's supposed to. It isn't supposed to cancel the entire submission of the form unless there is nothing else checked on the massUpdate.

2023-09-27 23:52 UTC, miigotu commented
Also, I don't even need to create the form there, there is already one on the massUpdate page I can append to that form and submit that. I'll revert this and make that change and do testing later. What browser are you using?

2023-09-28 00:29 UTC, miigotu requested changes

2023-09-28 00:29 UTC, miigotu commented on sickchill/gui/slick/js/core.js
>                          post: false,
This `post: false;` shouldn't be here

2023-09-28 00:29 UTC, miigotu commented on sickchill/gui/slick/js/core.js
>                          confirm() {
This is probably the problem:

This should not be a `confirm():` call, it should be `confirm: function () {`

Also, I need to check which version of jquery-confirm is being used because v3 is a completely different syntax and settings/config. v2.5.1 is the last version with a `confirm:` parameter.

Going to look at this here in a bit.

2023-09-28 03:59 UTC, BKSteve commented on sickchill/gui/slick/js/core.js
> +                    submit = false;
Yeah, was trying a solution. 
By setting to false here it stopped it skipping through the confirm and would then post the toDelete with the other to* items. 
It would never submit the toDelete ever.

2023-09-28 04:00 UTC, BKSteve commented on sickchill/gui/slick/js/core.js
>                          confirm() {
steep learning curve on this stuff.

2023-09-28 14:49 UTC, miigotu commented
Yeah it's ok, I get what you are trying to do, I just get frustrated when something doesn't work. It needs to be restructured more so all of the inputs are already handled. I have an almost finished commit to fix it, there should only be one path to submit.

2023-09-28 15:08 UTC, BKSteve commented
closed

2023-09-28 15:08 UTC, closed without merging