Support list of names passed to search in tvdb.py
SickChill/sickchill pull request #8758
Opened 2024-05-07 03:32 UTC by canepan

Currently, if a `list` is passed instead of a single `str`, it will fail the regex match

Fixes #

Proposed changes in this pull request:
- process each item if a list is passed

- [ ] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/SickChill/SickChill/blob/master/.github/CONTRIBUTING.md)

2024-05-12 10:37 UTC, BKSteve commented
What was SC doing at the time the `list` error was thrown?

2024-05-12 13:19 UTC, miigotu requested changes

2024-05-12 13:19 UTC, miigotu commented on sickchill/show/indexers/tvdb.py
> +        if isinstance(name, str):
Shouldn't this join the list like the other guessit fixes instead of just checking if it's a string?

On line 1 add:
```python
try:
    from collections import Iterable
except (ModuleNotFoundError, Import error):
    from collections.abc import Iterable
```
After line 106 add:
```python
if isinstance(name, Iterable) and  not isinstance(name, (str, bytes);
    name = " ".join(name)
```

Then remove the rest of the changes here (we know it's a string then)

2024-05-12 13:41 UTC, miigotu commented on sickchill/show/indexers/tvdb.py
> +        else:
Also this else needs removed. We don't want to search for ["fast", "&", "furious"] each individually, we want to join that list and search for the full string.

2024-05-13 14:34 UTC, canepan commented
What about instead enabling mypy type checking and avoid a series of checks used probably by a single caller?

⁣Nicola Canepa​

Il giorno 12 mag 2024, 14:41, alle ore 14:41, miigotu ***@***.***> ha scritto:
>@miigotu commented on this pull request.
>
>
>
>> +                        names.append(test.group(1).strip())
>+                    # Name with spaces
>+                    if re.match(r"[. -_]", name):
>+                        names.append(re.sub(r"[. -_]", " ",
>name).strip())
>+                        if test:
>+                            # Name with spaces and without year
>+                            names.append(re.sub(r"[. -_]", " ",
>test.group(1)).strip())
>+    
>+                for attempt in set(n for n in names if n.strip()):
>+                    try:
>+                        result = self._search(attempt,
>language=language)
>+                        if result:
>+                            break
>+                    except (requests.exceptions.RequestException,
>requests.exceptions.HTTPError, Exception):
>+                        logger.debug(traceback.format_exc())
>+        else:
>
>Also this else needs removed. We don't want to search for ["fast", "&",
>"furious"] each individually, we want to join that list and search for
>the full string.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/SickChill/sickchill/pull/8758#pullrequestreview-2051380727
>You are receiving this because you authored the thread.
>
>Message ID:
>***@***.***>

2024-05-23 19:26 UTC, miigotu commented
This has been fixed in #8759

2024-05-23 19:26 UTC, closed without merging